INSERT INTO DRUG_DETAILS (DRUG_ID,DRUG_NAME,EXPIRY_DATE,MANUFACTURE_DATE,MANUFACTURER) VALUES ('PR1', 'Paracetamol', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-11-2020', 'dd-MM-yyyy'), 'Farmson');
INSERT INTO DRUG_DETAILS (DRUG_ID,DRUG_NAME,EXPIRY_DATE,MANUFACTURE_DATE,MANUFACTURER) VALUES ('CR2', 'Crocin', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-11-2020', 'dd-MM-yyyy'), 'GSKAP');
INSERT INTO DRUG_DETAILS (DRUG_ID,DRUG_NAME,EXPIRY_DATE,MANUFACTURE_DATE,MANUFACTURER) VALUES ('PD3', 'Panadol', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-11-2020', 'dd-MM-yyyy'), 'GSK');
INSERT INTO DRUG_DETAILS (DRUG_ID,DRUG_NAME,EXPIRY_DATE,MANUFACTURE_DATE,MANUFACTURER) VALUES ('DD4', 'Dolo', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-11-2020', 'dd-MM-yyyy'), 'MicroLabs');


INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('1', 'Chennai', 500, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('2', 'Bangalore', 500, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('3', 'Pune', 500, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('4', 'Hyderabad', 500, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('5', 'Chennai', 500, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('6', 'Bangalore', 500, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('7', 'Pune', 500, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('8', 'Hyderabad', 500, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('9', 'Chennai', 500, 'PD3');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('10', 'Bangalore', 500, 'PD3');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('11', 'Hyderabad', 500, 'DD4');
INSERT INTO DRUG_LOCATION_DETAILS (SERIAL_ID,LOCATION,QUANTITY,DRUG_ID) VALUES('12', 'Bangalore', 500, 'DD4');